version: '3'
services:
  app:
    # image: node-yarn-api:latest
    build: ./
    volumes:
      - .:/app
    container_name: backend-app
    ports:
      - 8080:8080
    depends_on:
      - mongo
    environment:
      - DATABASE_URL=mongodb://root:teste@mongo-db:27017/azulou?authSource=admin

  mongo-db:
    image: mongo
    container_name: mongo-db
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste
