version: '3'
services:
  mongo-db:
    image: mongo
    container_name: mongo-db-default
    restart: always
    ports:
      - 27019:27017
    volumes:
      - ./mongo-volume:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste

