version: "3.1"
services:
  postgres:
    container_name: 'postgres'
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: db-example
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./bases:/home
    ports:
      - 5432:5432
