version: '3'
services:
  rabbitmq-server:
    image: rabbitmq:3-management
    container_name: rabbitmq-server
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./data:/var/lib/rabbitmq
    environment:
     - RABBITMQ_DEFAULT_USER=admin
     - RABBITMQ_DEFAULT_PASS=teste
